ip_forward: true
network_compression_threshold: 256
stats: 3a481ea7-811b-4fe4-bf31-8c07c1197399
groups:
  FireDragonZone:
  - admin
servers:
  lobby:
    motd: '&1Just another BungeeCord - lobby'
    address: localhost:10001
    restricted: false
  server2:
    motd: '&1Just another BungeeCord - server2'
    address: 192.168.0.119:10002
    restricted: false
  JamCity:
    motd: '&1Just another BungeeCord - JamCity'
    address: 192.168.0.119:10003
    restricted: false
  Test:
    motd: This is in fact a Test - Test
    address: 23.120.190.140:10004
    restricted: false
  McBall:
    motd: McBall
    address: 149.56.12.143
    restricted:false
timeout: 30000
player_limit: -1
listeners:
- query_port: 10000
  motd: '&1FireDragonZones Server!'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  - JamCity
  bind_local_address: true
  host: 192.168.0.119:10000
  max_players: 30
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
